### ISSUE TITLE
Unable to sync ethereum mainnet

### ISSUE THREAD

**Issue by let4be** [streamingfast/firehose-ethereum#52]
Following docs at
My config is as recommended is: https://firehose.streamingfast.io/firehose-setup/ethereum/installation-1

```yaml
start:
  args:
  # Define Firehose components that will be used for this setup
  - merger
  - firehose
  - reader-node
  - relayer
  - combined-index-builder
  flags:
    # Prevent creation of file for logging (logs from previous sessions are not visible with this setting)
    log-to-file: true

    # Ethereum is the default chain, its id is 1. Update these flags for different chains such as Binance
    common-chain-id: "1"
    common-network-id: "1"
    # Update the reader-node-path to reference the geth binary for the chain and OS being targeted
    reader-node-path: ../geth/eth_geth
    # Update the reader-code-arguments for the chain being targeted
    # Find specific values in the Firehose Ethereum Setup Documentation
    reader-node-arguments: "+--cache 8192 --maxpeers 100 --metrics --metrics.port 6061 --port=30303 --http.port=8545 --snapshot=true --txlookuplimit=1000"
    reader-node-log-to-zap: false

    firehose-grpc-listen-addr: ":9000"
    substreams-enabled: true
    #substreams-sub-request-parallel-jobs: 10
    #substreams-partial-mode-enabled: true
    substreams-rpc-endpoints: "$BSC_SUBSTREAMS_RPC_ENDPOINT"
    #substreams-sub-request-block-range-size: 100
    #substreams-stores-save-interval: 100
```

geth:
```
./eth_geth version
INFO [01-24|09:51:57.922] Initializing firehose 
INFO [01-24|09:51:57.926] Firehose initialized                     enabled=false sync_instrumentation_enabled=true mining_enabled=false block_progress_enabled=false compaction_disabled=false archive_blocks_to_keep=0 genesis_provenance="Geth Default" firehose_version=2.1 geth_version=1.10.26-fh2 chain_variant=geth
Geth
Version: 1.10.26-fh2
Git Commit: b47e39e956b6646f215f11b9a8a70ad03f733ab6
Architecture: amd64
Go Version: go1.17.13
Operating System: linux
GOPATH=
GOROOT=go
```

lots of such messages in logs:
```
WARN [01-24|09:47:44.328] Snapshot extension registration failed   peer=aab3bbde err="peer connected on snap without compatible eth support"
INFO [01-24|09:48:04.915] Looking for peers                        peercount=2 tried=37 static=0
WARN [01-24|09:50:01.325] Snapshot extension registration failed   peer=c5fb898d err="peer connected on snap without compatible eth support"
```

There's definitely something fishy is going on with node startup, I had the same intermittent issue with BSC mainnet
Any help welcomed
