### ISSUE TITLE
it sometimes takes mindreader a while to figure out geth is complete on shutdown

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-ethereum#7]
![image](https://user-images.githubusercontent.com/26171839/146814611-701ad78e-a132-419b-aac9-0ff5a6852a40.png)

This goes on until systemd reaches the programmed timeout and hard kills it.  I've seen this many, many times.

Seen both on BSC and ETH.

At least it is a clean shutdown so geth will start properly next time.

Config for BSC as example:
```
start:
  args:
  - mindreader-node
  flags:
    verbose: 2
    log-to-file: false
    common-chain-id: "56"
    common-network-id: "56"
    common-blocks-store-url: s3://ceph/.....
    common-oneblock-store-url: s3://ceph/.....
    mindreader-node-grpc-listen-addr: :9000
    mindreader-node-oneblock-suffix: servername
    mindreader-node-path: /usr/bin/geth
    mindreader-node-data-dir: /var/lib/geth
    mindreader-node-arguments: "+--port=30300 --cache=16384 --snapshot=false"
    mindreader-node-merge-and-store-directly: false
    mindreader-node-bootstrap-data-url: /etc/dfuse/genesis.json
```

This is not reproducible on demand. I'll try to note when it happens going forward.
